apiVersion: v1
kind: Pod
metadata:
 name: pod-with-init
spec:
  containers:
  - name: main
    image: nginx:latest
  initContainers:
    - name: init
      image: curlimages/curl:8.00.1
      command:
        - sh
        - -c
        - curl -s https://helloacm.com/api/fortune/

