apiVersion: v1
kind: Pod
metadata:
 name: pod-with-commands
spec:
  containers:
  - name: main
    image: busybox:latest
    command:
      - sh
      - -c
      - |
        ls -l
        echo "I'm done, but will hang on forever"
        sleep infinity
